language: julia
os:
    - osx
    - linux
julia:
    - 0.6
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.add("FDM")'
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.build("SmoothCurves"); Pkg.test("SmoothCurves"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("SmoothCurves")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    # - julia -e 'cd(Pkg.dir("SmoothCurves")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
